apiVersion: v2
name: cloudnative-pg
description: CloudNativePG Operator for PostgreSQL on Kubernetes
type: application
version: 1.0.0
appVersion: 1.30.0
dependencies:
  - name: cloudnative-pg
    version: 0.29.0
    repository: https://cloudnative-pg.github.io/charts
