{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-discord-webhook.fullname" . }}
  labels:
    {{- include "alertmanager-discord-webhook.labels" . | nindent 4 }}
type: Opaque
data:
  discord-webhook-url: {{ .Values.discord.webhookURL | b64enc | quote }}
{{- end }}
