apiVersion: v2
name: traefik
description: Vendored Traefik Helm chart for uttutu homelab
type: application
version: 1.0.0
appVersion: v3.7.5
dependencies:
  - name: traefik
    version: 41.0.0
    repository: https://traefik.github.io/charts
