apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-iresharma
  namespace: cert-manager
spec:
  secretName: wildcard-iresharma-tls
  commonName: "*.iresharma.com"
  dnsNames:
    - "*.iresharma.com"
    - "iresharma.com"
  issuerRef:
    name: letsencrypt-prod-iresh
    kind: ClusterIssuer
  renewBefore: 360h