apiVersion: v2
name: kube-prometheus-stack
description: Vendored kube-prometheus-stack Helm chart for uttutu homelab
type: application
version: 1.0.0
appVersion: v0.92.0
dependencies:
  - name: kube-prometheus-stack
    version: 87.1.0
    repository: https://prometheus-community.github.io/helm-charts
