apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.superuserSecret.name }}
  namespace: {{ .Values.postgres.namespace }}
  labels:
    cnpg.io/cluster: {{ .Values.postgres.name }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.superuserSecret.username | default "postgres" | quote }}
  password: {{ .Values.postgres.superuserSecret.password | default (randAlphaNum 32) | quote }}
