apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Values.kafka.namespace }}
  annotations:
    strimzi.io/pod-recovery: enabled
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    listeners:
      {{- toYaml .Values.kafka.listeners | nindent 6 }}
    config:
      {{- toYaml .Values.kafka.config | nindent 6 }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
