{{- range .Values.tenant_rbac.namespaces }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-resource-quota
  namespace: {{ . }}
  labels:
    app.kubernetes.io/managed-by: helm
spec:
  hard:
    requests.cpu: {{ .Values.tenant_rbac.resourceQuota.requests.cpu | quote }}
    requests.memory: {{ .Values.tenant_rbac.resourceQuota.requests.memory | quote }}
    limits.cpu: {{ .Values.tenant_rbac.resourceQuota.limits.cpu | quote }}
    limits.memory: {{ .Values.tenant_rbac.resourceQuota.limits.memory | quote }}
    persistentvolumeclaims: {{ .Values.tenant_rbac.resourceQuota.persistentvolumeclaims | quote }}
    requests.storage: {{ .Values.tenant_rbac.resourceQuota.requests.storage | quote }}
    pods: {{ .Values.tenant_rbac.resourceQuota.pods | quote }}
---
{{- end }}