apiVersion: v2
name: local-path-provisioner
description: Local path dynamic provisioner for Strimzi Kafka
type: application
version: 1.0.0
appVersion: 0.0.37
dependencies:
  - name: local-path-provisioner
    version: 0.0.37
    repository: "oci://ghcr.io/rancher/local-path-provisioner/charts"
