apiVersion: v2
name: prometheus-pushgateway
description: Vendored prometheus-pushgateway Helm chart for homelab
type: application
version: 1.0.0
appVersion: v1.11.3
dependencies:
  - name: prometheus-pushgateway
    version: 3.8.0
    repository: https://prometheus-community.github.io/helm-charts
