prometheus-pushgateway:
  replicaCount: 1

  persistence:
    enabled: true
    storageClass: nfs-csi-pve2
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
    interval: 30s

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
